//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWCFClientApp
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WeatherForecast", Namespace = "http://schemas.datacontract.org/2004/07/TestWCFService.Models")]
    public partial class WeatherForecast : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string DateField;

        private string SummaryField;

        private int TemperatureCField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemperatureC
        {
            get
            {
                return this.TemperatureCField;
            }
            set
            {
                this.TemperatureCField = value;
            }
        }
    }



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IWeatherService")]
    public interface IWeatherService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeatherService/GetWeatherforecast", ReplyAction = "http://tempuri.org/IWeatherService/GetWeatherforecastResponse")]
        WeatherForecast[] GetWeatherforecast();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeatherService/GetWeatherforecast", ReplyAction = "http://tempuri.org/IWeatherService/GetWeatherforecastResponse")]
        System.Threading.Tasks.Task<WeatherForecast[]> GetWeatherforecastAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeatherService/UpdateForecast", ReplyAction = "http://tempuri.org/IWeatherService/UpdateForecastResponse")]
        string UpdateForecast(WeatherForecast forecast);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeatherService/UpdateForecast", ReplyAction = "http://tempuri.org/IWeatherService/UpdateForecastResponse")]
        System.Threading.Tasks.Task<string> UpdateForecastAsync(WeatherForecast forecast);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherServiceChannel : IWeatherService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceClient : System.ServiceModel.ClientBase<IWeatherService>, IWeatherService
    {

        public WeatherServiceClient()
        {
        }

        public WeatherServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public WeatherServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public WeatherForecast[] GetWeatherforecast()
        {
            return base.Channel.GetWeatherforecast();
        }

        public System.Threading.Tasks.Task<WeatherForecast[]> GetWeatherforecastAsync()
        {
            return base.Channel.GetWeatherforecastAsync();
        }

        public string UpdateForecast(WeatherForecast forecast)
        {
            return base.Channel.UpdateForecast(forecast);
        }

        public System.Threading.Tasks.Task<string> UpdateForecastAsync(WeatherForecast forecast)
        {
            return base.Channel.UpdateForecastAsync(forecast);
        }
    }
}
